apiVersion: automation.cloudbees.io/v1alpha1
name: Gitleaks Scanner
kind: workflow

on:
  push:
    branches:
      - master

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  gitleaks-hybrid-scan:
    steps: 

      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello smoke test
        shell: sh
        run: |
          echo "hello world!"
          ls -la

      - name: checkout Source Code
        uses: cloudbees-io/checkout@v1

