name: Gosec Scan

on:
  push:
    branches:
      - master

jobs:
  gosec:
    name: Run Gosec to detect vuln
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gosec cloudbees action
        uses: https://github.com/cloudbees-io/gosec-sast-scan-code@v1
