name: Gosec Scan

on:
  push:
    branches:
      - mastery

jobs:
  gosec:
    name: Run Gosec to detect vuln
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gosec cloudbees action
        uses: cloudbees-io/gosec-plugin@v2
        with:
            cb_token: "cb_api_nR9WIDmLG2PDCgeEjFFg5G6xPA6h4ofhEaSKX79ENcHIHRaH8EfWgc3Ebj7OTL4JXzBEuSDUwC07TP1+ANwxAw=="
            cb_api_url: "https://api.saas-preprod.beescloud.com"
            gh_run_id: ${GITHUB_RUN_ID}"
            gh_job_id: ${GITHUB_JOB}"
            gh_step_id: ${GITHUB_STEP_NAME}"
