name: Gosec Scan

on:
  push:
    branches:
      - master

jobs:
  gosec:
    name: Run Gosec to detect vuln
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gosec cloudbees action
        uses: cloudbees-io/gosec-plugin@v1
